# Generated by Django 2.0.4 on 2018-05-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('portid', models.IntegerField(primary_key=True, serialize=False)),
                ('portname', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('variant', models.TextField(default='')),
                ('portdir', models.TextField(default='')),
                ('platform', models.TextField(default='')),
                ('cur_version', models.TextField(default='')),
                ('license', models.TextField(default='')),
                ('long_desc', models.TextField(default='')),
                ('homepage', models.TextField(default='')),
            ],
        ),
    ]
