# Generated by Django 2.0.4 on 2018-05-06 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='port',
            old_name='git_url_path',
            new_name='homepage',
        ),
    ]
