# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0002_auto_20180404_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='description',
            field=models.TextField(),
        ),
    ]
